### ISSUE TITLE
Clean up get help implementation

### ISSUE THREAD

**Issue by sikander-94** [CodeTheChangeUBC/btg-site#32]
When sending emails, the return from the 'POST' request in getHelpViewController.js seems to always enter to failure case, even when emails are succesfully sent. This may have to do with how the post(/sendEmail) returning (maybe not returning a success code, I don't know).

Also, it would be nice if the user got some confirmation of the email being sent and also when the submit button is submitted it would be nice for the form fields to be set to empty. For this reason I think it might be better to use $http rather than $.ajax since I think the former is the angular equivalent of JQuery's ajax. I dont think we have access to our scope variables in $.ajax but I'm not sure, since I wasn't able to set the $scope.name, email, and message fields to blank on success or on error.

**Comment by iRule95** [comment]
$.ajax should be the equivalent of the jQuerry ajax method. Creating a closure around it should solve the problem. I could take a look if need be.

**Comment by iRule95** [comment]
Usually in such cases, there are success/error messages shown near the submit button, and while submitting there should be a spinner or some other loading signal to indicate to the user that the form is being submitted. 

We could potentially also disable the submit button to prevent the user from submitting the request multiple times but that case should be handled regardless of what we show to the user.

**Comment by sikander-94** [comment]
@iRule95 yeah if you can take a look that would be great! Just add yourself as an assignee on this issue :)

**Comment by alfaeddie** [comment]
This feature is still in the works guys, I was planning on continuing work on it. But I just wanted to get the initial working version into master. @iRule95 are you already working on this?

**Comment by sikander-94** [comment]
@alfaeddie ah okay sorry about that!

**Comment by iRule95** [comment]
@alfaeddie nope I haven't.

**Comment by alfaeddie** [comment]
Is it alright if i take it? I've just sat down to start working on this stuff

**Comment by iRule95** [comment]
@alfaeddie sure go ahead.
